version: '3.5'
services:
  python:
    build: .
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
    volumes:
      - ./:/opt/social_warehouse_pg_data
    restart: always
    networks:
      - social_warehouse_network
  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
    ports:
      - 54323:5432
    volumes:
      - social_warehouse_pg_data:/var/lib/postgresql
      - .pg_hba.conf:/etc/pg_hba.conf
    restart: always
    networks:
      - social_warehouse_network
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8082:8080"
    restart: always
    networks:
      - social_warehouse_network

volumes:
  social_warehouse_pg_data:
    external: true
    name: social_warehouse_pg_data

networks:
  social_warehouse_network:
    driver: bridge